spring:
  application:
    name: askTheStars-BE
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star
    username: root
    password: 1234
  
mybatis: 
    type-aliases-package: com.solji.star.*
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:Mybatis-Config.xml

server:
  port: 80

debug: false